language: node_js
node_js:
  - "stable"

install:
 - npm install

services:
  - postgresql

scripts: npm run test

script:
  - nyc --reporter=lcov npm run test

services:
  - postgresql

before_script:
  - psql -c 'create database ah_zinnia;' -U postgres

script:
  - nyc --reporter=lcov npm run test

after_success:
  - npm run coverage
