language: node_js
node_js:
  - 'LTS'

install:
  - npm install

services:
  - postgresql

scripts: npm run test

before_script:
  - psql -c 'create database ah_zinnia;' -U postgres

after_success:
  - npm run coveralls
